self.addEventListener("install",e=>{
 e.waitUntil(
  caches.open("cs-cache").then(c=>
   c.addAll([
    "./",
    "./index.html",
    "./script.js"
   ])
  )
 )
})
self.addEventListener("fetch",e=>{
 e.respondWith(
  caches.match(e.request).then(r=>r||fetch(e.request))
 )
})
